In [1]:
import warnings
warnings.simplefilter('ignore')

In [2]:
import numpy as np
import pandas as pd

In [3]:
import matplotlib.pyplot as pt

In [4]:
%matplotlib inline

In [5]:
df=pd.read_csv("C:\\Users\\aedur\\Downloads\\Admission_Predict (2).csv")

In [6]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

    Research  Chance of Admit   
0        Yes              0.92  
1        Yes              0.76  
2        Yes              0.72  
3        Yes              0.80  
4         No              0.65  
..       ...               ...  
395      Yes              0.82  
396      Yes              0.84  
397      Yes              0.91  
398       No              0.67  
399      Yes              0.95  

[400 rows x 9 columns]

In [19]:
x=df.iloc[:,1:6].values
y=df.iloc[:,-1].values.reshape(-1,1)

In [9]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [20]:
y

array([[0.92],
       [0.76],
       [0.72],
       [0.8 ],
       [0.65],
       [0.9 ],
       [0.75],
       [0.68],
       [0.5 ],
       [0.45],
       [0.52],
       [0.84],
       [0.78],
       [0.62],
       [0.61],
       [0.54],
       [0.66],
       [0.65],
       [0.63],
       [0.62],
       [0.64],
       [0.7 ],
       [0.94],
       [0.95],
       [0.97],
       [0.94],
       [0.76],
       [0.44],
       [0.46],
       [0.54],
       [0.65],
       [0.74],
       [0.91],
       [0.9 ],
       [0.94],
       [0.88],
       [0.64],
       [0.58],
       [0.52],
       [0.48],
       [0.46],
       [0.49],
       [0.53],
       [0.87],
       [0.91],
       [0.88],
       [0.86],
       [0.89],
       [0.82],
       [0.78],
       [0.76],
       [0.56],
       [0.78],
       [0.72],
       [0.7 ],
       [0.64],
       [0.64],
       [0.46],
       [0.36],
       [0.42],
       [0.48],
       [0.47],
       [0.54],
       [0.56],
       [0.52],
       [0.55],
       [0.

In [21]:
x

array([[337. , 118. ,   4. ,   4.5,   4.5],
       [324. , 107. ,   4. ,   4. ,   4.5],
       [316. , 104. ,   3. ,   3. ,   3.5],
       ...,
       [330. , 116. ,   4. ,   5. ,   4.5],
       [312. , 103. ,   3. ,   3.5,   4. ],
       [333. , 117. ,   4. ,   5. ,   4. ]])

In [10]:
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [23]:
y_test

array([[0.71],
       [0.7 ],
       [0.79],
       [0.73],
       [0.72],
       [0.48],
       [0.77],
       [0.71],
       [0.9 ],
       [0.94],
       [0.58],
       [0.89],
       [0.72],
       [0.57],
       [0.78],
       [0.42],
       [0.64],
       [0.84],
       [0.63],
       [0.72],
       [0.9 ],
       [0.83],
       [0.57],
       [0.47],
       [0.85],
       [0.67],
       [0.44],
       [0.54],
       [0.92],
       [0.62],
       [0.68],
       [0.73],
       [0.73],
       [0.61],
       [0.55],
       [0.74],
       [0.64],
       [0.89],
       [0.73],
       [0.95],
       [0.71],
       [0.72],
       [0.75],
       [0.76],
       [0.86],
       [0.7 ],
       [0.39],
       [0.79],
       [0.61],
       [0.64],
       [0.71],
       [0.8 ],
       [0.61],
       [0.89],
       [0.68],
       [0.79],
       [0.78],
       [0.52],
       [0.76],
       [0.88],
       [0.74],
       [0.49],
       [0.65],
       [0.59],
       [0.87],
       [0.89],
       [0.

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
lm=LinearRegression()

In [26]:
lm.fit(x_train,y_train)

LinearRegression()

In [27]:
ypredict=lm.predict(x_test)

In [28]:
ypredict

array([[0.70495406],
       [0.69291556],
       [0.78568707],
       [0.6061276 ],
       [0.7072867 ],
       [0.61266304],
       [0.69047488],
       [0.70123163],
       [0.84580681],
       [0.91939541],
       [0.5355264 ],
       [0.88723487],
       [0.74162195],
       [0.51781579],
       [0.85874756],
       [0.60496869],
       [0.60353639],
       [0.76946379],
       [0.63949446],
       [0.74132672],
       [0.90220947],
       [0.8782899 ],
       [0.63308567],
       [0.48060521],
       [0.77983364],
       [0.58969337],
       [0.48580374],
       [0.66387244],
       [0.93032265],
       [0.69042713],
       [0.6487936 ],
       [0.75485794],
       [0.73610957],
       [0.5224955 ],
       [0.80669824],
       [0.7818399 ],
       [0.72816583],
       [0.838756  ],
       [0.62862955],
       [0.89615978],
       [0.74981328],
       [0.70783332],
       [0.77099694],
       [0.81241033],
       [0.8446517 ],
       [0.76371325],
       [0.64793911],
       [0.742

In [30]:
x_test

array([[309. , 105. ,   5. ,   3.5,   3.5],
       [308. , 110. ,   4. ,   3.5,   3. ],
       [326. , 110. ,   3. ,   3.5,   3.5],
       [306. , 105. ,   2. ,   3. ,   2.5],
       [316. , 105. ,   3. ,   3. ,   3.5],
       [309. , 100. ,   2. ,   3. ,   3. ],
       [312. , 109. ,   3. ,   3. ,   3. ],
       [312. , 104. ,   3. ,   3.5,   4. ],
       [332. , 118. ,   2. ,   4.5,   3.5],
       [331. , 117. ,   4. ,   4.5,   5. ],
       [300. , 105. ,   1. ,   1. ,   2. ],
       [333. , 113. ,   5. ,   4. ,   4. ],
       [320. , 110. ,   2. ,   4. ,   3.5],
       [302. ,  99. ,   1. ,   2. ,   2. ],
       [328. , 112. ,   4. ,   4. ,   4.5],
       [311. , 104. ,   2. ,   2. ,   2. ],
       [312. ,  98. ,   1. ,   3.5,   3. ],
       [329. , 110. ,   2. ,   4. ,   3. ],
       [315. ,  99. ,   2. ,   3.5,   3. ],
       [313. , 107. ,   3. ,   4. ,   4.5],
       [329. , 119. ,   4. ,   4.5,   4.5],
       [327. , 113. ,   4. ,   4.5,   5. ],
       [301. , 106. ,   4. ,   2

In [31]:
comparison=pd.DataFrame(x_test,columns=["input Data","input Data1","input Data2","input Data3","input Data4"])

In [32]:
comparison["AVL O/P"]=y_test

In [33]:
comparison

input Data  input Data1  input Data2  input Data3  input Data4  AVL O/P
0        309.0        105.0          5.0          3.5          3.5     0.71
1        308.0        110.0          4.0          3.5          3.0     0.70
2        326.0        110.0          3.0          3.5          3.5     0.79
3        306.0        105.0          2.0          3.0          2.5     0.73
4        316.0        105.0          3.0          3.0          3.5     0.72
..         ...          ...          ...          ...          ...      ...
75       311.0        104.0          3.0          3.5          2.0     0.61
76       306.0        103.0          2.0          2.5          3.0     0.69
77       313.0        106.0          2.0          2.5          2.0     0.62
78       334.0        116.0          4.0          4.0          3.5     0.93
79       297.0         96.0          2.0          2.5          1.5     0.43

[80 rows x 6 columns]

In [34]:
comparison["Pred_O/P"]=ypredict

In [35]:
comparison

input Data  input Data1  input Data2  input Data3  input Data4  AVL O/P  \
0        309.0        105.0          5.0          3.5          3.5     0.71   
1        308.0        110.0          4.0          3.5          3.0     0.70   
2        326.0        110.0          3.0          3.5          3.5     0.79   
3        306.0        105.0          2.0          3.0          2.5     0.73   
4        316.0        105.0          3.0          3.0          3.5     0.72   
..         ...          ...          ...          ...          ...      ...   
75       311.0        104.0          3.0          3.5          2.0     0.61   
76       306.0        103.0          2.0          2.5          3.0     0.69   
77       313.0        106.0          2.0          2.5          2.0     0.62   
78       334.0        116.0          4.0          4.0          3.5     0.93   
79       297.0         96.0          2.0          2.5          1.5     0.43   

    Pred_O/P  
0   0.704954  
1   0.692916  
2   0.785687  
3   0.606128  
4   0.707287  
..       ...  
75  0.625947  
76  0.611429  
77  0.627317  
78  0.874822  
79  0.476725  

[80 rows x 7 columns]